#!/bin/bash
# Copyright (C) 2015  Beniamine, David <David@Beniamine.net>
# Author: Beniamine, David <David@Beniamine.net>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

usage()
{
    echo "Usage $0 [options] -- cmd args"
    echo "Options:"
    echo "-b            Do black and white plots"
    echo "-s            Save plots (pdf files)"
    echo "-t            Disable titles in figures"
    echo "-r            Run only (do not plot)"
    echo "-i            Do not ignore smally used structures. This might
                        produce a hard to read output"
    echo "-p bench      Do not run, plot only for benchmark named benc"
    echo "-S scale      Set the scale for saved figures implies -s"
    echo "-h            pDisplay this help and quit"
}

run=true
plot=true
titles=T
bw=F
save=F
ignore=TRUE
scale=1
while getopts "trbshp:S:i" opt; do
    case $opt in
        i)
            ignore=FALSE
            ;;
        r)
            plot=false
            ;;
        t)
            titles=F
            ;;
        b)
            bw="T"
            ;;
        p)
            run=false
            PROG="$OPTARG"
            ;;
        s)
            save="T"
            ;;
        S)
            scale="$OPTARG"
            save="T"
            ;;
        h)
            usage
            exit 0
            ;;
        \?)
            echo "Invalid option : -$OPTARG" >&2
            usage
            exit 1
            ;;
    esac
done

if $run
then
    set -o errexit -o nounset -o pipefail

    # directory of this script
    DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

    # recompile pintool if necessary
    (cd $DIR; make -q || make)

    # program to trace and its arguments
    PROGARGS=$(echo ${@} | sed s,.*--\ ,,)
    PROG=$(echo $PROGARGS | { read first rest; echo $(basename $first) | sed s,\\s.*,, ; } )


    # finally, run pin
    echo -e "\n\n## running pin: $PROGARGS"

    set -x
    time -p pin -xyzzy -enable_vsm 0 -t $DIR/obj-*/*.so -- $PROGARGS
    set +x

    # sort output page csv's according to page address
    for f in $PROG.*.page.csv; do
        sort -n -t, -k 1,1 -o $f $f
    done
fi

if $plot
then
    dir=$(pwd)
    cd $(dirname $0)
    mkdir figure/
    lstopo --no-io figure/topo.png
    Rscript plot.R $dir $PROG $save $bw $titles $scale $ignore
    # Clean and copi figures
    rm -rf $dir/figure
    mv ./figure $dir/
    cd -
    mv ./$PROG*.pdf ./figure/ > /dev/null 2>&1
fi
